### ISSUE TITLE
EPIC: Запустить CI

### ISSUE THREAD

**Issue by artbear** [silverbulleters/add#14]
- [x]  простой CI на ci.sb.org аналогично VB2
- [x]  CI на ci.sb.org аналогично основному VB

- [x]  Sonar

- [x]  Параллельная сборка на разных платформах
- [x]  Подготовка сборки типовой Windows и Linux ноды

**Comment by artbear** [comment]
@pumbaEO @nixel2007 @allustin 
Кто сможет запустить `CI на ci.sb.org аналогично существующему VB` ?
пока проверка только на 8.3.10

**Comment by artbear** [comment]
сделано.
